# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
    push:
        branches: 
            - main
    pull_request:
        branches: 
            - main

jobs:    
    build-and-tests-iOS:
        runs-on: macos-latest
        name: "Build and test on iOS target"
        steps:
            - uses: actions/checkout@v3
            - uses: maxim-lobanov/setup-xcode@v1.5.1
            - run: xcodebuild clean build test -workspace EssentialApp/EssentialApp.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    
    build-and-tests-macOS:
        runs-on: macos-latest
        name: "Build and test on macOS target"
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3
            - name: "Checkout"
              uses: maxim-lobanov/setup-xcode@v1.5.1
            - run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
