# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
    push:
    branches: [ "main" ]
    pull_request:
    branches: [ "main" ]

jobs:
    
    setup-xcode:
        - name: Setup Xcode version
            uses: maxim-lobanov/setup-xcode@v1.5.1
    
    build-and-tests-iOS:
    
        runs-on: ios-latest
    
        steps:
            - uses: actions/checkout@v3
            with: xcode-version: latest-stable
    
            - name: Build and test
            run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    
    build-and-tests-macOS:
    
        runs-on: macos-latest
    
        steps:
            - uses: actions/checkout@v3
            with: xcode-version: latest-stable
    
            - name: Build and test
            run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
